version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.0-node-browsers
      environment:
        DATABASE_HOST:          localhost
        APP_NAME:               amazon_calc
        DATABASE_USERNAME:      ubuntu
        RAILS_ENV:              test
        CIRCLE_CI_RUBY_VERSION: 2.5.0
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: ubuntu
        POSTGRES_DB:   amazon_calc_test

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}

        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    - run: bundle exec rake db:create
    - run: bundle exec rake db:schema:load

    - run:
        name:    Rubocop
        command: bundle exec rubocop

    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results